version: '3.9'

services:
  product_service:
    container_name: product_service
    build: ./product_service
    ports:
      - "8001:8000"
    environment:
      - JWT_SECRETE=jwt_secrete

  mongo_product:
    container_name: mongo_product
    image: bitnami/mongodb

  auth_service:
    container_name: auth_service
    build: ./user_service
    ports:
      - "8002:8000"
    environment:
      JWT_SECRETE: jwt_secrete

  api_gateway:
    image: devopsfaith/krakend:watch
    container_name: api_gateway
    volumes:
      - ./krakenD:/etc/krakend
    ports:
      - "8080:8080"

    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    depends_on:
      - product_service
      - auth_service
    #      - category_service
    environment:
      - JWT_SECRETE=jwt_secrete
