name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the test Docker image
      run: | 
        cd  product_service
        docker build . --file Dockerfile.test -t product-service
    - name: Run the test Docker image
      run: |
        docker run product-service
